### ISSUE TITLE
plot_emb_circle_scale() output low resolutation image

### ISSUE THREAD

**Issue by zhenzuo2** [hansenlab/tricycle#3]
Hi,

My data has about 100, 000 cells and the figure generated by plot_emb_circle_scale() is of poor image quality (huge pixels).

```
png(some_output_path,
    units = "in", width = 15, height = 15, res = 600)
p <- plot_emb_circle_scale(sce, dimred = "UMAP", point.size = 0.5, point.alpha = 1) +
  theme_bw(base_size = 14)
legend <- circle_scale_legend(text.size = 5, alpha = 0.9)
plot_grid(p, legend, ncol = 2, rel_widths = c(1, 0.4))
dev.off()
```

I am not sure if it is caused by large sample size or default raster() argument. I can attach output image if needed.

**Comment by zhenzuo2** [comment]
![Screenshot 2021-11-02 135154](https://user-images.githubusercontent.com/13971930/139927140-6ee6a360-75fc-40aa-b4e6-a49e0edfa8d1.png)

**Comment by sjczheng** [comment]
Could you make a pdf file to see how it looks?

**Comment by sjczheng** [comment]
And have you tried changing your res values in the png function?

**Comment by zhenzuo2** [comment]
```
pdf(path_to_save,
    width = 15, height = 15)
p <- plot_emb_circle_scale(sce, dimred = "UMAP", point.size = 0.5, point.alpha = 1) +
  theme_bw(base_size 
![Screenshot 2021-11-02 135154](https://user-images.githubusercontent.com/13971930/139928967-c0cc7787-b076-4e7b-9fbb-5c6291a21be6.png)
= 14)
legend <- circle_scale_legend(text.size = 5, alpha = 0.9)
plot_grid(p, legend, ncol = 2, rel_wi
![Screenshot 2021-11-02 135154](https://user-images.githubusercontent.com/13971930/139929029-0fb1a054-0e18-4c46-8613-efb67f81c3f4.png)
dths = c(1, 0.4))
dev.off()
```

It does not work. I also tried ggsave(). But none of them worked.

**Comment by zhenzuo2** [comment]
![Screenshot 2021-11-02 135154](https://user-images.githubusercontent.com/13971930/139929059-6bdd5cb2-a746-4de2-857d-087b98edd7b8.png)


> And have you tried changing your res values in the png function?

res = 600 is pretty high. It usually generated 20M figures. But the png saved by plot_emb_circle_scale() is less than 1M.

**Comment by sjczheng** [comment]
Yes. You are right. The size of the figure is much smaller than a regular ggplot scatter plot.
The reason is that I use scatter more package (https://github.com/exaexa/scattermore) to plot the points.
It seems like a rater issue by scattermore package.
Could you change the point.size to 1 in plot_emb_circle_scale function to test?
I kind of remember there is an issue if you use point.size less than 1 in scattermore.

**Comment by zhenzuo2** [comment]
![Screenshot 2021-11-02 135154](https://user-images.githubusercontent.com/13971930/139939534-5d2f6a9d-7c34-4cb3-9c7f-f072c8e4a0d4.png)

**Comment by zhenzuo2** [comment]
Thank you. scattermore is much faster than a regular ggplot scatter plot. Rasterization may be a problem when raster size is too large.

**Comment by sjczheng** [comment]
Yeah. You may need to paly a little with the figure size to make it work.
It seems to me that your figure size is too big.

**Comment by kasperdanielhansen** [comment]
Worth sending a report to scattermore authors

Best,
Kasper
(Sent from my phone.)
