### ISSUE TITLE
Projection on UMAP

### ISSUE THREAD

**Issue by s849** [hansenlab/tricycle#5]
Hello,

Thank you for developing such an amazing tool. I am wondering if you can provide a better example on how to project the results on an existing UMAP? I am having trouble performing this step.

Thank you!

**Comment by sjczheng** [comment]
Hello,

If you operate on SingleCellExperiment object (sce.o), say you have a reduceDim named as "UMAP".
You can visualize the results by 

```R
plot_emb_circle_scale(sce.o, dimred = "UMAP")
```

Best,
Shijie
