### ISSUE TITLE
Error when using gname.type = "ENSEMBL" and species = "human"

### ISSUE THREAD

**Issue by vleblanc** [hansenlab/tricycle#9]
Hello!

I'm trying to run TriCycle on a human dataset with ENSEMBL IDs, and I get the following error:

`Error in mapIds_base(x, keys, column, keytype, ..., multiVals = multiVals) : 
  argument "column" is missing, with no default`

I've narrowed this down to the `tricycle:::.humanSymbol` function and the `AnnotationDbi::mapIDs` function within it, where the `columns` argument (plural) should be `column` (singular).

In case this is a version issue, here's my session info:

> R version 4.1.2 (2021-11-01)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS:   /gsc/software/linux-x86_64-centos7/R-4.1.2/lib64/R/lib/libRblas.so
> LAPACK: /gsc/software/linux-x86_64-centos7/R-4.1.2/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] tricycle_1.2.1              SingleCellExperiment_1.16.0 SummarizedExperiment_1.24.0 Biobase_2.54.0             
>  [5] GenomicRanges_1.46.1        GenomeInfoDb_1.30.1         IRanges_2.28.0              S4Vectors_0.32.4           
>  [9] BiocGenerics_0.40.0         MatrixGenerics_1.6.0        matrixStats_0.62.0         
> 
> loaded via a namespace (and not attached):
>  [1] viridis_0.6.2             httr_1.4.4                BiocSingular_1.10.0       viridisLite_0.4.1        
>  [5] bit64_4.0.5               DelayedMatrixStats_1.16.0 scuttle_1.4.0             assertthat_0.2.1         
>  [9] blob_1.2.3                cellranger_1.1.0          vipor_0.4.5               GenomeInfoDbData_1.2.7   
> [13] yaml_2.3.5                ggrepel_0.9.1             pillar_1.8.1              RSQLite_2.2.17           
> [17] lattice_0.20-45           glue_1.6.2                beachmat_2.10.0           digest_0.6.29            
> [21] RColorBrewer_1.1-3        XVector_0.34.0            colorspace_2.0-3          htmltools_0.5.3          
> [25] Matrix_1.5-1              pkgconfig_2.0.3           zlibbioc_1.40.0           purrr_0.3.4              
> [29] mvtnorm_1.1-3             scales_1.2.1              ScaledMatrix_1.2.0        BiocParallel_1.28.3      
> [33] tibble_3.1.8              KEGGREST_1.34.0           generics_0.1.3            ggplot2_3.3.6            
> [37] cachem_1.0.6              cli_3.4.0                 readxl_1.4.1              magrittr_2.0.3           
> [41] crayon_1.5.1              evaluate_0.16             memoise_2.0.1             fansi_1.0.3              
> [45] beeswarm_0.4.0            tools_4.1.2               scater_1.22.0             org.Hs.eg.db_3.14.0      
> [49] lifecycle_1.0.1           munsell_0.5.0             DelayedArray_0.20.0       irlba_2.3.5              
> [53] AnnotationDbi_1.56.2      Biostrings_2.62.0         compiler_4.1.2            rsvd_1.0.5               
> [57] rlang_1.0.4               scattermore_0.8           grid_4.1.2                RCurl_1.98-1.8           
> [61] BiocNeighbors_1.12.0      rstudioapi_0.14           circular_0.4-95           rmarkdown_2.16           
> [65] bitops_1.0-7              boot_1.3-28               gtable_0.3.1              DBI_1.1.3                
> [69] R6_2.5.1                  gridExtra_2.3             knitr_1.40                dplyr_1.0.10             
> [73] fastmap_1.1.0             bit_4.0.4                 utf8_1.2.2                ggbeeswarm_0.6.0         
> [77] parallel_4.1.2            Rcpp_1.0.9                vctrs_0.4.1               png_0.1-7                
> [81] tidyselect_1.1.2          xfun_0.31                 sparseMatrixStats_1.6.0

**Comment by sjczheng** [comment]
Hi,

Sorry for the delayed reply.
Yes. It is a version issue. 
The issue had been fixed in a previous update.
You could update your package to avoid the issue.

Best,
Shijie
